# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets, QtCore
from PySide6.QtCore import QMetaObject, QSize, Qt
from PySide6.QtWidgets import QLabel, QLineEdit, QPlainTextEdit, QPushButton, QSizePolicy

from videotrans.configure.config import tr
from videotrans.util import tools


class Ui_cosyvoiceform(object):
    def setupUi(self, cosyvoiceform):
        self.has_done = False
        if not cosyvoiceform.objectName():
            cosyvoiceform.setObjectName("cosyvoiceform")
        cosyvoiceform.setWindowModality(Qt.NonModal)
        cosyvoiceform.resize(640, 420)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(cosyvoiceform.sizePolicy().hasHeightForWidth())
        cosyvoiceform.setSizePolicy(sizePolicy)
        cosyvoiceform.setMaximumSize(QSize(640, 420))

        # 创建一个垂直布局
        v1 = QtWidgets.QVBoxLayout(cosyvoiceform)
        tipslabel = QLabel(tr('cosyvoice23webui'))
        tipslabel.setWordWrap(True)
        v1.addWidget(tipslabel)

        # WebUI URL
        h1 = QtWidgets.QHBoxLayout()
        self.label = QLabel()
        self.label.setObjectName("label")
        self.label.setMinimumSize(QSize(0, 35))
        self.api_url = QLineEdit()
        self.api_url.setObjectName("api_url")
        self.api_url.setMinimumSize(QSize(0, 35))
        h1.addWidget(self.label)
        h1.addWidget(self.api_url)
        v1.addLayout(h1)

        # 全局 instruct 文本（情感/方言/风格指令）
        h1_prompt = QtWidgets.QHBoxLayout()
        self.lbl_prompt = QLabel(tr('Instruct'))
        self.lbl_prompt.setMinimumSize(QSize(70, 35))
        self.instruct_text = QLineEdit()
        self.instruct_text.setObjectName("instruct_text")
        self.instruct_text.setMinimumSize(QSize(0, 35))
        self.instruct_text.setPlaceholderText(
            tr('Optional. Examples: 用四川话说 / 兴奋开心地说 / 用悲伤的语气说')
        )
        h1_prompt.addWidget(self.lbl_prompt)
        h1_prompt.addWidget(self.instruct_text)
        v1.addLayout(h1_prompt)

        # 内置 SFT 音色列表（英文逗号分隔）
        v_sft = QtWidgets.QVBoxLayout()
        v_sft.addWidget(QLabel(tr('Built-in SFT voices (comma separated; leave empty for clone only)')))
        self.sft_roles = QPlainTextEdit()
        self.sft_roles.setObjectName("sft_roles")
        self.sft_roles.setPlaceholderText('中文男,中文女,英文男,英文女,日语男,韩语女,粤语女')
        self.sft_roles.setMinimumSize(QSize(0, 110))
        self.sft_roles.setMaximumHeight(140)
        v_sft.addWidget(self.sft_roles)
        v1.addLayout(v_sft)

        # 推理 seed
        h_seed = QtWidgets.QHBoxLayout()
        self.lbl_seed = QLabel(tr('Seed (0 = random)'))
        self.lbl_seed.setMinimumSize(QSize(150, 35))
        self.seed = QLineEdit()
        self.seed.setObjectName("seed")
        self.seed.setMinimumSize(QSize(0, 35))
        self.seed.setPlaceholderText('0')
        h_seed.addWidget(self.lbl_seed)
        h_seed.addWidget(self.seed)
        v1.addLayout(h_seed)

        # 操作按钮区
        h2 = QtWidgets.QHBoxLayout()
        self.save = QPushButton()
        self.save.setObjectName("save")
        self.save.setMinimumSize(QSize(0, 35))

        self.test = QPushButton()
        self.test.setObjectName("test")
        self.test.setMinimumSize(QSize(0, 35))

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/cosyvoice'))

        h2.addWidget(self.save)
        h2.addWidget(self.test)

        ref_btn = QtWidgets.QPushButton()
        ref_btn.setText(tr("Set reference audio"))
        ref_btn.clicked.connect(tools.show_refaudio_win)
        h2.addWidget(ref_btn)
        h2.addWidget(help_btn)

        v1.addLayout(h2)

        self.retranslateUi(cosyvoiceform)

        QMetaObject.connectSlotsByName(cosyvoiceform)

    def retranslateUi(self, cosyvoiceform):
        cosyvoiceform.setWindowTitle("CosyVoice2/3")
        self.save.setText(tr("Save"))
        self.api_url.setPlaceholderText("webui url http://127.0.0.1:8000")
        self.label.setText("WebUI url")
        self.test.setText(tr("Test"))
